# Generated by Django 6.0.2 on 2026-02-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
