# Generated by Django 6.0.2 on 2026-02-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=100)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_app.tbl_movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_app.tbl_user')),
            ],
        ),
    ]
