# Generated by Django 6.0.2 on 2026-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0002_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_movie',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
