# Generated by Django 6.0.2 on 2026-02-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0003_tbl_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_movie',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
