# Generated by Django 6.0.2 on 2026-02-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0004_alter_tbl_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
