# Generated by Django 6.0.2 on 2026-02-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0005_alter_tbl_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_movie',
            name='rating',
            field=models.FloatField(),
        ),
    ]
