# Generated by Django 6.0.2 on 2026-02-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0006_alter_tbl_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='otp_field',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
