# Generated by Django 6.0.2 on 2026-02-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0007_tbl_user_email_tbl_user_otp_field_tbl_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
