# Generated by Django 6.0.2 on 2026-02-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0008_tbl_user_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='otp_field',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='verified',
        ),
    ]
