# Generated by Django 6.0.2 on 2026-03-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0009_remove_tbl_user_email_remove_tbl_user_otp_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='email',
            field=models.EmailField(default='sample@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
